import { User, Vendor, RFQ, Quotation, PurchaseOrder, Invoice, AuditLog } from './types'

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@vendorbridge.com',
    name: 'John Admin',
    role: 'admin',
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    email: 'manager@vendorbridge.com',
    name: 'Sarah Manager',
    role: 'procurement_manager',
    createdAt: new Date('2024-01-05'),
  },
  {
    id: '3',
    email: 'finance@vendorbridge.com',
    name: 'Mike Finance',
    role: 'finance',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '4',
    email: 'vendor@acmesupplies.com',
    name: 'Bob Vendor',
    role: 'vendor',
    company: 'Acme Supplies',
    createdAt: new Date('2024-02-01'),
  },
]

export const mockVendors: Vendor[] = [
  {
    id: '1',
    name: 'Acme Supplies Inc',
    email: 'sales@acmesupplies.com',
    contactPerson: 'John Smith',
    address: '123 Main St',
    city: 'New York',
    country: 'USA',
    phoneNumber: '+1-555-0101',
    website: 'acmesupplies.com',
    rating: 4.5,
    status: 'active',
    categories: ['Electronics', 'Components'],
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '2',
    name: 'Global Parts Ltd',
    email: 'info@globalparts.com',
    contactPerson: 'Jane Doe',
    address: '456 Oak Ave',
    city: 'London',
    country: 'UK',
    phoneNumber: '+44-20-7123-4567',
    website: 'globalparts.com',
    rating: 4.8,
    status: 'active',
    categories: ['Industrial Parts', 'Raw Materials'],
    createdAt: new Date('2023-11-15'),
    updatedAt: new Date('2024-06-05'),
  },
  {
    id: '3',
    name: 'Tech Solutions Europe',
    email: 'contact@techsol.eu',
    contactPerson: 'Klaus Mueller',
    address: '789 Tech Park',
    city: 'Berlin',
    country: 'Germany',
    phoneNumber: '+49-30-555-8888',
    rating: 4.2,
    status: 'active',
    categories: ['Software', 'IT Services'],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-06-03'),
  },
  {
    id: '4',
    name: 'Quality Manufacturing Co',
    email: 'sales@qualitymfg.com',
    contactPerson: 'Robert Chen',
    address: '321 Factory Blvd',
    city: 'Shanghai',
    country: 'China',
    phoneNumber: '+86-21-5888-8888',
    rating: 3.9,
    status: 'active',
    categories: ['Manufacturing', 'Custom Production'],
    createdAt: new Date('2023-09-10'),
    updatedAt: new Date('2024-05-28'),
  },
]

export const mockRFQs: RFQ[] = [
  {
    id: '1',
    number: 'RFQ-2024-001',
    title: 'Electronic Components Supply',
    description: 'Need reliable supply of microcontrollers and passive components for Q3 2024',
    items: [
      {
        id: '1',
        description: 'ARM Cortex-M4 Microcontroller',
        quantity: 5000,
        unit: 'pieces',
        estimatedPrice: 12,
        specifications: 'STM32H7 series or equivalent',
      },
      {
        id: '2',
        description: 'Ceramic Capacitors 100nF',
        quantity: 50000,
        unit: 'pieces',
        estimatedPrice: 0.05,
      },
    ],
    estimatedBudget: 100000,
    dueDate: new Date('2024-07-15'),
    status: 'published',
    createdBy: '2',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-02'),
    vendors: ['1', '2'],
  },
  {
    id: '2',
    number: 'RFQ-2024-002',
    title: 'Office Equipment Lease',
    description: 'Looking for office equipment rental and leasing services',
    items: [
      {
        id: '3',
        description: 'Multifunction Printer/Scanner',
        quantity: 50,
        unit: 'units',
        estimatedPrice: 200,
      },
    ],
    estimatedBudget: 50000,
    dueDate: new Date('2024-07-20'),
    status: 'published',
    createdBy: '2',
    createdAt: new Date('2024-06-05'),
    updatedAt: new Date('2024-06-05'),
    vendors: ['3'],
  },
]

export const mockQuotations: Quotation[] = [
  {
    id: '1',
    rfqId: '1',
    vendorId: '1',
    quotationNumber: 'QT-2024-001',
    items: [
      {
        id: '1',
        rfqItemId: '1',
        description: 'ARM Cortex-M4 Microcontroller',
        quantity: 5000,
        unit: 'pieces',
        unitPrice: 11.5,
        totalPrice: 57500,
      },
      {
        id: '2',
        rfqItemId: '2',
        description: 'Ceramic Capacitors 100nF',
        quantity: 50000,
        unit: 'pieces',
        unitPrice: 0.048,
        totalPrice: 2400,
      },
    ],
    totalAmount: 59900,
    validUntil: new Date('2024-07-01'),
    deliveryDate: new Date('2024-08-15'),
    paymentTerms: 'Net 30',
    status: 'submitted',
    notes: 'Volume discounts available for larger orders',
    createdAt: new Date('2024-06-08'),
    updatedAt: new Date('2024-06-08'),
  },
  {
    id: '2',
    rfqId: '1',
    vendorId: '2',
    quotationNumber: 'QT-2024-002',
    items: [
      {
        id: '3',
        rfqItemId: '1',
        description: 'ARM Cortex-M4 Microcontroller',
        quantity: 5000,
        unit: 'pieces',
        unitPrice: 12,
        totalPrice: 60000,
      },
      {
        id: '4',
        rfqItemId: '2',
        description: 'Ceramic Capacitors 100nF',
        quantity: 50000,
        unit: 'pieces',
        unitPrice: 0.05,
        totalPrice: 2500,
      },
    ],
    totalAmount: 62500,
    validUntil: new Date('2024-07-02'),
    deliveryDate: new Date('2024-09-01'),
    paymentTerms: 'Net 45',
    status: 'submitted',
    createdAt: new Date('2024-06-09'),
    updatedAt: new Date('2024-06-09'),
  },
]

export const mockPOs: PurchaseOrder[] = [
  {
    id: '1',
    poNumber: 'PO-2024-001',
    vendorId: '1',
    rfqId: '1',
    quotationId: '1',
    items: [
      {
        id: '1',
        description: 'ARM Cortex-M4 Microcontroller',
        quantity: 5000,
        unit: 'pieces',
        unitPrice: 11.5,
        totalPrice: 57500,
        receivedQuantity: 2500,
      },
      {
        id: '2',
        description: 'Ceramic Capacitors 100nF',
        quantity: 50000,
        unit: 'pieces',
        unitPrice: 0.048,
        totalPrice: 2400,
        receivedQuantity: 50000,
      },
    ],
    totalAmount: 59900,
    orderDate: new Date('2024-06-10'),
    deliveryDate: new Date('2024-08-15'),
    paymentTerms: 'Net 30',
    status: 'partial_delivery',
    notes: 'First batch delivered on schedule',
    createdBy: '2',
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-20'),
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: '1',
    invoiceNumber: 'INV-2024-001',
    poId: '1',
    vendorId: '1',
    items: [
      {
        id: '1',
        description: 'ARM Cortex-M4 Microcontroller',
        quantity: 2500,
        unit: 'pieces',
        unitPrice: 11.5,
        totalPrice: 28750,
      },
      {
        id: '2',
        description: 'Ceramic Capacitors 100nF',
        quantity: 50000,
        unit: 'pieces',
        unitPrice: 0.048,
        totalPrice: 2400,
      },
    ],
    totalAmount: 31150,
    dueDate: new Date('2024-07-10'),
    invoiceDate: new Date('2024-06-15'),
    paymentStatus: 'paid',
    paymentMethod: 'Bank Transfer',
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-25'),
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: '1',
    userId: '2',
    action: 'CREATE',
    entityType: 'RFQ',
    entityId: '1',
    changes: { status: 'published' },
    timestamp: new Date('2024-06-01'),
  },
  {
    id: '2',
    userId: '1',
    action: 'UPDATE',
    entityType: 'Vendor',
    entityId: '1',
    changes: { rating: 4.5 },
    timestamp: new Date('2024-06-02'),
  },
]
